"""Auto-generated built-in glossary terms data."""

BUILTIN_TERMS = [
    ('1,4-二硫苏糖醇', '1,4-Dithiothreitol', 'DTT'),
    ('13mm抗生素瓶铝塑组合盖', '13mm Flip-off seal', 'Datwyler'),
    ('2000L一次性反应器', '2000L Single-Use Bioreactor', None),
    ('200L一次性反应器', '200L Single-Use Bioreactor', None),
    ('20mm抗生素瓶铝塑组合盖', '20mm Flip-off seal', 'Datwyler'),
    ('6000L反应器', '6000L Bioreactor', None),
    ('BWS-27型精密恒温水槽', 'Precision Temperature-Controlled Water Bath(Model BWS-27)', None),
    ('C末端赖氨酸缺失', 'C-terminal lysine truncation', None),
    ('DNA残留', 'DNA Residual', None),
    ('HCP残留', 'HCP Residual', None),
    ('L-蛋氨酸亚砜亚胺', 'L-Methionine Sulfoximine', 'MSX'),
    ('N,N-二甲基乙酰胺', 'N,N-Dimethylacetamide', 'DMA'),
    ('N-乙酰神经氨酸', 'N-Acetylneuraminic acid', None),
    ('N-羟乙酰神经氨酸', 'N-glycolylneuraminic acid', None),
    ('N端焦谷氨酸环化', 'N-terminal pyroglutamic acid cyclization', None),
    ('N糖基化位点', 'N-glycosylation site', None),
    ('N糖糖型', 'N-glycans', None),
    ('N糖谱', 'N-glycan profiling', None),
    ('Protein A残留', 'Protein A Residual', None),
    ('Q环化', 'Gln->Pyro-Glu', None),
    ('一次性储液袋', 'single-use storage bag', None),
    ('一次性移液管', 'Disposable Pipette', None),
    ('一次性配液袋', 'single-use liquid preparation bag', None),
    ('一般工艺参数', 'General process parameter', None),
    ('上海乐纯生物技术股份有限公司', 'Shanghai LePure Biotech Co., Ltd.', None),
    ('上海倍锦生物科技有限公司', 'Shanghai Beijin Biotech Co., Ltd.', None),
    ('不对称因子', 'Asymmetry', None),
    ('不溶性微粒', 'sub-visual particle', 'SVP'),
    ('不适用', 'Not Applicable', None),
    ('专业术语使用管理规程', 'Management Procedure for Use of Technical Terms', None),
    ('世代', 'Population Doubling Level', 'PDL'),
    ('中心点', 'Center Point', None),
    ('中硼硅玻璃管制注射剂瓶', 'Injection vial made of middle borosilicate glass tubing', None),
    ('中试', 'Pilot Site', None),
    ('中间体', 'Intermediate', None),
    ('中间过程控制', 'In Process Control', None),
    ('中间过程检测', 'In Process Test', None),
    ('主细胞库', 'Master Cell Bank', 'MCB'),
    ('二氧化碳培养箱', 'CO2 Incubator', None),
    ('二甲基亚砜', 'Dimethyl Sulfoxide', 'DMSO'),
    ('二硫化甲脒二盐酸盐', 'Formamidine disulfide dihydrochloride', 'FDS.2HCl'),
    ('二硫键连接', 'Disulfide bond linkage', None),
    ('二级碎片信息', 'MS/MS fragmentation data', None),
    ('交叉污染', 'Cross-contamination', None),
    ('产品共线', 'Shared-line', None),
    ('产品切换', 'Product Changeover', None),
    ('产品收率', 'Product yield', None),
    ('亲和层析', 'Affinity Chromatography', None),
    ('亲和层析中和', 'Affinity Chromatography Neutralization', None),
    ('传代', 'passage', None),
    ('传代代次', 'Passage', 'P'),
    ('传代稳定性研究', 'Passage stability study', None),
    ('低 pH 病毒灭活', 'Low pH Virus Inactivation', None),
    ('低水平', 'Low Level', None),
    ('使用前、灭菌后完整性测试', 'PUPSIT（Pre-Use Post-Sterilization Integrity Test）', None),
    ('保留时间', 'Residence Time', None),
    ('倍增时间', 'Doubling Time', 'DT'),
    ('偏差', 'Mass error', None),
    ('偶联', 'Conjugation', 'Conjugation'),
    ('偶联位点', 'Conjugate Site', None),
    ('偶联反应', 'Conjugation reaction', 'CON'),
    ('偶联物', 'Conjugates', 'Conjugates'),
    ('傅里叶变换红外光谱', 'Fourier Transform Infrared spectroscopy', None),
    ('克隆', 'Clone', None),
    ('克隆筛选', 'Clone Screening', None),
    ('全柱成像毛细管等电聚焦', 'Imaging Capillary Isoelectric Focusing', 'icIEF'),
    ('关键工艺参数', 'Critical process parameter', None),
    ('关键质量', 'critical quality', None),
    ('内毒素', 'Endotoxin', None),
    ('冗余过滤系统', 'redundant filtration system', None),
    ('冲洗', 'Flush', None),
    ('冻存', 'Cryopreserved', None),
    ('冻存管', 'Freezing Vial', None),
    ('冻干', 'lyophilization', 'Lyo'),
    ('冻干机', 'lyophilizer', None),
    ('冻干粉饼', 'lyophilized cake', None),
    ('冻融', 'Freeze-Thaw', 'FT-5 cyc'),
    ('分子排阻色谱', 'Size Exclusion Chromatography', None),
    ('分子粒径', 'Molecular particle size', None),
    ('分枝杆菌', 'Mycobacterium Detection', None),
    ('判定标准', 'Acceptance Criterion', None),
    ('制剂', 'Drug production', 'DP'),
    ('制剂缓冲液', 'Formulation Buffer', 'Formulation Buffer'),
    ('剂型', 'Dosage form', None),
    ('动态光散射法', 'Dynamic Light Scattering', None),
    ('包材', 'Container', None),
    ('包装', 'Packaging', None),
    ('升华干燥', 'Primary drying', None),
    ('单体峰', 'Monomer peak', None),
    ('单克隆化', 'Single Cell Cloning', None),
    ('单克隆成像设备', 'Monoclonal Imager', None),
    ('单因素', 'One Factor', None),
    ('单抗', 'monoclonal antibody', 'mAb'),
    ('单细胞打印机', 'Single Cell Printer', None),
    ('南京化学试剂股份有限公司', 'Nanjing Chemical Reagent Co., LTD', None),
    ('压力升', 'pressure rise', None),
    ('压力差', 'Delta Pressure', None),
    ('原始细胞库', 'Primary Cell Bank', 'PCB'),
    ('原液', 'Drug substance', 'DS'),
    ('原液生产上游工艺规程', 'Drug Substance Upstream Manufacturing Process Procedure', None),
    ('去卷积处理', 'Deconvoluted', None),
    ('参数拟订分类', 'Preliminary Classification', None),
    ('反应器', 'bioreactor', None),
    ('反应器培养间', 'Cell Culture Room', None),
    ('反应器扩增', 'Bioreactor-Based Cell Expansion', None),
    ('反应器扩增间', 'Upstream Cell Expansion Room', None),
    ('取样计划表', 'Sampling Plan List', None),
    ('变性还原', 'Denaturation and reduction', None),
    ('可发现性', 'Detection', 'Detection'),
    ('可抽提体积', 'extractable volume', None),
    ('可接受范围', 'Acceptable Range', None),
    ('可接受范围 / 可接受标准', 'Acceptable Range', None),
    ('可见异物', 'visible particles', None),
    ('吸附深层过滤', 'Adsorption Depth Filtration', None),
    ('四川金山制药有限公司', 'Sichuan Jinshan Pharmaceutical Co., Ltd.', None),
    ('固定蛋白含量', 'fixed protein content', None),
    ('国械注准', 'NMPA No.', None),
    ('在位清洗', 'Clean In Place', None),
    ('在线配液系统', 'In-line Buffer Preparation System', None),
    ('均方根误差', 'Root mean square error', None),
    ('基础培养基', 'Basal Medium', None),
    ('塌陷及萎缩', 'collapse and shrinkage', None),
    ('处方', 'Formulation', None),
    ('复溶', 'reconstitution', None),
    ('复苏', 'Vial Thaw', None),
    ('复苏和摇瓶扩增', 'Cell Recovery and Shake Flask Expansion', None),
    ('外包间', 'Packaging room', None),
    ('外源性病毒体外测试', 'Exogenous virus in vitro assay', None),
    ('外源病毒检测', 'Adventitious Virus Detection', None),
    ('多分散系数', 'Polydispersity Index', None),
    ('多参数研究', 'Multi-Parameter Study', None),
    ('大清场', 'Line Clearance for  Product  Changeover', None),
    ('大片段缺失', 'Large Fragment Truncation', None),
    ('孔板', 'Well Plate', None),
    ('完整分子量', 'Intact mass', None),
    ('实测分子量', 'Measured mass', None),
    ('客户', 'client', None),
    ('宿主细胞', 'Host Cell', None),
    ('宿主细胞 DNA', 'Host Cell DNA', None),
    ('宿主细胞蛋白', 'Host Cell Protein', None),
    ('小料配制间', 'Preparation Room for Material with Small Quantity', None),
    ('小清场', 'Line Clearance', None),
    ('山东祥瑞药业有限公司', 'Shandong Xiangrui Pharmaceutical Co., LTD', None),
    ('工作服', 'Working Garment', None),
    ('工作细胞库', 'Working Cell Bank', 'WCB'),
    ('工艺参数', 'process parameters', None),
    ('工艺开发部', 'Process Development', 'PD'),
    ('工艺性能确认', 'Process Performance Qualification', None),
    ('工艺表征', 'Process Characterization', None),
    ('工艺验证', 'process validation', None),
    ('差示扫描荧光法', 'Differential scanning fluorimetry', None),
    ('差示扫描量热法', 'Differential scanning calorimetry', None),
    ('平均粒径', 'Average Size', None),
    ('平衡', 'Holding', None),
    ('建库', 'Banking', None),
    ('异常事件', 'Abnormal Event', None),
    ('微生物负载', 'bioburden', None),
    ('微生物限度', 'Bioburden', None),
    ('德鲁替康', 'Deruxtecan', 'DXd'),
    ('性能属性', 'Performance Attribute', None),
    ('总离子色谱图', 'Total ion chromatogram', None),
    ('成品', 'Drug production', 'DP'),
    ('扩散流', 'diffusive flow', None),
    ('批次切换', 'Batch Changeover', None),
    ('抗体偶联药物', 'Antibody-Drug Conjugates', 'ADCs'),
    ('抗体寡核苷酸偶联物', 'Antibody−Oligonucleotide Conjugates', 'AOCs'),
    ('抗生素瓶和输液瓶用铝塑组合盖', 'Flip-off seal', 'Datwyler'),
    ('拷贝数', 'Copy number', None),
    ('振荡培养箱', 'Orbital Shaking Incubator', None),
    ('探针', 'Probe', None),
    ('接种间', 'Cell Inoculation Room', None),
    ('摇瓶', 'Shake Flask', None),
    ('摇管', 'Spin Tube', None),
    ('操作范围', 'Operating Range', None),
    ('支原体', 'Mycoplasma', None),
    ('支原体检查', 'Mycoplasma Detection', None),
    ('收率', 'Yield', None),
    ('收获罐', 'Harvest Tank', None),
    ('收获间', 'Harvest Room', None),
    ('收集液', 'Pool', None),
    ('无菌', 'Sterility', None),
    ('无菌工艺模拟试验', 'Aseptic Process Simulation Test', None),
    ('无菌生产工艺', 'Aseptic  Production  Process', None),
    ('无锡耐思生命科技股份有限公司', 'Wuxi NEST Biotechnology Co., Ltd.', None),
    ('易于控制的关键工艺参数', 'Well Controlled-Critical Process Parameter', None),
    ('易控制的关键工艺参数', 'Well-Controlled Critical Process Parameter', None),
    ('智享', 'Intellectivebio', None),
    ('智享生物', 'Intellectivebio', None),
    ('最差条件', 'Worst Case', None),
    ('杭州科百特过滤器材有限公司', 'Hangzhou Cobetter Filtration Equipment Co., Ltd.', None),
    ('柱体积', 'Column Volume', None),
    ('样品份数', 'sample units', None),
    ('样品位置分布图', 'sample location map', None),
    ('核酸适配体前药偶联物', 'Aptamer−PolyproDrug Conjugates', 'ApPDCs'),
    ('核酸适配体药物偶联物', 'Aptamer−Drug Conjugates', 'ApDCs'),
    ('欧洲动物细胞培养物保藏中心', 'European Collection of Animal Cell Culture Authenticated', 'ECACC'),
    ('母液', 'condition buffer', None),
    ('每日可接受暴漏量', 'Acceptable Daily Exposure', 'ADE'),
    ('气相液氮罐', 'Vapor Phase Liquid Nitrogen Tank', None),
    ('氨基酸序列覆盖率', 'Sequence coverage', None),
    ('水侵入', 'water intrusion', None),
    ('水分含量', 'Moisture content', None),
    ('江苏省勤奋药业有限公司', 'Jiangsu Province Qinfen Pharmaceutical Co., Ltd.', None),
    ('污染', 'Contamination', None),
    ('河北华晨药业集团有限公司', 'Hebei Huachen Pharmaceutical Group Co., LTD', None),
    ('泡点法', 'bubble point', None),
    ('波浪式反应器', 'Wave Bioreactor', None),
    ('注射制剂瓶用铝塑组合盖', 'Aluminium-plastics Combination Caps for Injectable Drug Bottles', 'West'),
    ('注射制剂用氯化丁基橡胶塞', 'Chlorobutyl Rubber Stopper for Injectable Drug', 'West'),
    ('注射制剂用溴化丁基橡胶塞', 'Bromobutyl Rubber Stopper for Injectable Drug', 'West'),
    ('注射剂，冻干粉针', 'Lyophilized powder for injection', None),
    ('注射听觉提示', 'Audible Feedback', None),
    ('注射完毕视觉提示', 'Visual Feedback', None),
    ('注射液和注射用无菌粉末用涂膜溴化丁基橡胶塞', 'serum stopper', 'Datwyler'),
    ('注射用冷冻干燥用溴化丁基橡胶塞', 'Lyo stopper', 'Datwyler'),
    ('注射用水', 'Water for Injection', None),
    ('洁净工作台', 'Clean bench', None),
    ('洗滤缓冲液', 'DF Buffer', None),
    ('活塞', 'Plunger Stopper', None),
    ('活细胞密度', 'Viable Cell Density', 'VCD'),
    ('活细胞密度峰值', 'Peak Viable Cell Density', 'PVCD'),
    ('流加', 'Fed-batch', None),
    ('流加培养', 'Fed-batch culture', None),
    ('流加评估', 'Fed-batch evaluation', 'FB'),
    ('浊度', 'Turbidity', None),
    ('液相色谱质谱联用', 'Liquid chromatography-mass spectrometry', None),
    ('混淆', 'Mix-up', None),
    ('湖北葛店人福药用辅料有限责任公司', 'Hubei Gedian Humanwell Pharmaceutical Excipients Co., Ltd.', None),
    ('溶氧', 'Dissolved Oxygen', None),
    ('澄清过滤', 'Clarification', None),
    ('澄清过滤系统', 'Clarification Filtration System', None),
    ('灌流', 'Perfusion', None),
    ('烷基化', 'Alkylation', None),
    ('爬壁', 'fogging', None),
    ('爬壁高度', 'fogging height', None),
    ('牛多瘤病毒', 'Bovine Polyoma Virus', None),
    ('牛杯状病毒', 'Bovine Calicivirus', None),
    ('牛海绵状脑病', 'Bovine Spongiform Encephalopathy', 'BSE'),
    ('物料平衡', 'Material balance', None),
    ('物料清单', 'Bill of material', None),
    ('特征', 'characteristics', None),
    ('特殊取样', 'Special Sampling', None),
    ('猪/牛圆环病毒', 'Porcine & Bovine Circovirus', None),
    ('猪牛源病毒检测', 'Porcine &Bovine Virus Detection', None),
    ('珠海西格膜生物技术有限公司', 'Zhuhai Singleuse Biotechnology Co., Ltd.', None),
    ('理论分子量', 'Theoretical mass', None),
    ('理论塔板数', 'Number Of Theoretical Plates', None),
    ('琥珀酰亚胺', 'Succinimide', None),
    ('生产技术部', 'Manufacturing Science and Technology', None),
    ('生产指令', 'Production Order', None),
    ('生产部', 'Manufacturing', None),
    ('生化分析仪', 'Biochemical Analyzer', None),
    ('生物安全柜', 'Biological Safety Cabinet', 'BSC'),
    ('电动移液器', 'Electric Pipette', None),
    ('电转杯', 'Electroporation Cuvette', None),
    ('疏水作用层析', 'Hydrophobic Interaction Chromatography', None),
    ('百万分之一', 'Parts Per Million', 'ppm'),
    ('百林科制药装备科技（江苏）有限公司', 'Bio-Link Pharma Equipment Technology (Jiangsu) Co., Ltd.', None),
    ('百林科（兰州）新材料有限公司', 'Bio-Link (Lanzhou) Applied Materials Co., Ltd.', None),
    ('研发质量保证', 'Research Quality Assurance', 'RQA'),
    ('离子源', 'Ion source', None),
    ('程序降温盒', 'Programmed Freezing Box', None),
    ('笔帽拔除力', 'Pen cap removal force', None),
    ('笔式注射器用溴化丁基橡胶活塞', 'Bromobutyl Rubber Plungers for Pen-injectors', 'West'),
    ('第一轮', 'Round 1', None),
    ('等高线作图', 'Contour Mapping', None),
    ('糖基化肽段', 'Glycosylated peptide', None),
    ('紫外 280 nm 消光系数法', 'Absorbance 280 nm', None),
    ('纤维和微粒', 'fibres and particles', None),
    ('组件', 'components/assembly', None),
    ('组装进度约1/4时', 'Approximately 1/4 assembly complete', None),
    ('细胞培养收获液', 'Harvest Cell Culture Fluid', None),
    ('细胞库', 'Cell Bank', None),
    ('细胞建库', 'Cell Banking', None),
    ('细胞建库部', 'Cell Banking', 'CB'),
    ('细胞扩增', 'Cell Expansion', None),
    ('细胞株开发', 'Cell Line Development', 'CLD'),
    ('细胞池', 'Pool', None),
    ('细胞活性', 'cell based assay', None),
    ('细胞活率', 'Cell viability', None),
    ('细胞种属鉴定', 'Cell Identity', None),
    ('细胞计数仪', 'Cell Counter', None),
    ('细菌、真菌检测', 'Bacteria and Fungus Detection', None),
    ('细菌截留测试', 'bacterial retention testing', None),
    ('终止反应', 'Quenching', None),
    ('终止收集点', 'Stop Collection Point', None),
    ('维布妥昔单抗', 'Brentuximab Vedotin', 'Adcetris'),
    ('缓冲液配制', 'Buffer Preparation', None),
    ('缓存罐', 'Holding Tank', None),
    ('羟基化', 'Hydroxylation', None),
    ('翻译后修饰', 'Post-translation Modifications', None),
    ('聚体峰', 'Dimer peak', None),
    ('聚合体', 'High molecular weight', 'HMW'),
    ('肽段', 'Peptides', None),
    ('胰酪大豆胨液体培养基', 'Tryptone Soy  Broth  Medium', None),
    ('脱氢抗坏血酸', 'Dehydroascorbic acid', 'DHAA'),
    ('脱盐换液', 'Desalting/buffer exchange', None),
    ('脱糖修饰', 'Deglycosylated', None),
    ('脱糖完整分子量', 'Deglycosylated intact mass', None),
    ('脱糖肽段', 'Deglycosylated peptide', None),
    ('脱糖部分还原分子量', 'Deglycosylated partially reduced mass', None),
    ('脱酰胺', 'Deamidation', None),
    ('荧光超高效液相色谱', 'Fluorescence ultra high-performance liquid chromatography', None),
    ('药物-连接子', 'Drug-linker', 'DL'),
    ('药物抗体偶联比率', 'Drug-to-Antibody Ratio', 'DAR'),
    ('葡聚糖硫酸酯钠盐', 'Dextran Sulfate Sodium Salt', 'DS'),
    ('蛋白浓度', 'Protein concentration', None),
    ('螺原体检测', 'Spiroplasma Detection', None),
    ('血气分析仪', 'Blood Gas Analyzer', None),
    ('补料培养基', 'Feed Medium', None),
    ('表达载体构建', 'Vector Construction', None),
    ('表达量', 'Titer', None),
    ('裸抗', 'monoclonal antibody', 'mAb'),
    ('西格玛奥德里奇（无锡）生化科技有限公司', 'Sigma-Aldrich (Wuxi) Biochemical Technology Co., Ltd.', None),
    ('规格', 'Type', None),
    ('解析干燥', 'Secondary drying', None),
    ('设定值', 'Set Point', None),
    ('调节缓冲液', 'Condition Buffer', 'Condition Buffer'),
    ('质粒', 'Plasmid', None),
    ('质荷比', 'Mass-to-charge ratio (m/z)', None),
    ('质谱仪', 'Mass Spectrometry', None),
    ('质量标准', 'Specification', None),
    ('质量检测器', 'Mass detector', None),
    ('赖氨酸缺失', 'K loss', None),
    ('起始收集点', 'Start Collection Point', None),
    ('超低温冰箱', 'Ultra Low Temperature Freezer', None),
    ('超滤/洗滤', 'Ultrafiltration / Diafiltration', None),
    ('超滤浓缩换液', 'Ultrafiltration/Diafiltration', None),
    ('超滤缓冲液', 'DF buffer', None),
    ('跨膜压', 'Transmembrane Pressure', None),
    ('转染', 'Transfection', None),
    ('载体', 'Vector', None),
    ('载荷', 'payload', None),
    ('辅料母液', 'Condition Buffer', None),
    ('过滤器两端压差', 'pressure difference across the filter', None),
    ('过量灌装', 'overfilling volume', None),
    ('连接子', 'Linker', None),
    ('连续流离心+澄清收获', 'Harvest and Clarification', None),
    ('连续流离心机', 'Continuous Flow Centrifuge', None),
    ('迷你细胞池', 'Minipool', None),
    ('退火', 'Annealing', None),
    ('逆转录病毒检测', 'Retrovirus Detection', None),
    ('通量衰减', 'Flux decay', None),
    ('部分还原', 'Partially reduced', None),
    ('部分还原分子量', 'Partially reduced mass', None),
    ('配伍', 'in-use', None),
    ('配伍稳定性', 'in-use stability', None),
    ('配制流程', 'Preparation Procedure', None),
    ('酶切', 'Digestion', None),
    ('酶联免疫吸附测定法', 'Enzyme-linked Immunosorbent Assay', 'Elisa'),
    ('酸碱度', 'Potential of Hydrogen', None),
    ('醋酸', 'Acetic Acid', 'HAC'),
    ('重均分子量', 'Weight Average MW', None),
    ('重要工艺参数', 'Key process parameter', None),
    ('重链+轻链', 'Heavy chain+Light chain', 'HC+LC'),
    ('阳离子交换层析', 'Cation Exchange Chromatography', None),
    ('阴离子交换层析', 'Anion Exchange Chromatography', None),
    ('降解剂药物偶联物', 'Degrader−Drug Conjugates', 'DACs'),
    ('除病毒过滤', 'Virus Filtration', None),
    ('除菌过滤器', 'sterile sterilising grade filter', None),
    ('震荡', 'Agitation', None),
    ('非标计分析仪', 'Gator Prime', None),
    ('顶洗', 'Chase', None),
    ('预充式注射笔', 'Prefilled Injection Pen', None),
    ('预充针', 'Pre-filling Needle', None),
    ('预冻', 'Freezing', None),
    ('预测刻画器图', 'Prediction Profiler Plot', None),
    ('预灌封注射器', 'prefilled syringe', None),
    ('预灌封注射器用玻璃针管（带注射针）', 'Pre-filled syringe （with neddle）', 'PFS'),
    ('额外取样计划表', 'Additional  Sampling Plan List', None),
    ('风险排序及筛选', 'Risk Ranking and Filtering', None),
    ('高分辨质谱仪', 'High-Resolution Mass Spectrometry', None),
    ('高水平', 'High Level', None),
    ('鼠源特异性病毒检测', 'Rodent Specific Virus Detection', None),
    ('鼠细小病毒', 'Minute Virus of Mice', 'MVM'),
]
